"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[username]
show_always = true

[golang]
symbol = "î˜§ "
style = "bold blue"

[nodejs]
detect_files = [
  'package.json',
  '.nvmrc',
  '.node-version',
  '!bunfig.toml',
  '!bun.lockb',
]
